### ISSUE TITLE
English corrections for index.md

### ISSUE THREAD

**Issue by ruiokada** [Rokt33r/rokt33r.github.io#3]
Hi, sorry for lurking your website. I saw that you are not completely fluent in English and for some personal reasons I feel obligated to let you know that there are some mistakes on your profile page.

> An Entrepreneur who **enjoying** programming.
> -> An Entrepreneur who **enjoys** programming.

> English(broken, though **I’d** been working at **the** US company)
> -> English(broken, though **I’ve** been working at **a** US company)

> Chief **Pruduct** Officer
> -> Chief **Product** Officer

**Comment by Rokt33r** [comment]
Thank you!
